# -*- coding: utf-8 -*-
"""OnlyRAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16yb0PPAA1tBToYPZ0db8jIOo_qEZo3L7
"""

#Installiamo le librerie necessarie
# !pip install -q sentence-transformers faiss-cpu pandas numpy

#Importiamo le librerie
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np
import pandas as pd
from pathlib import Path
import json

#Montare Google Drive
# from google.colab import drive
# drive.mount('/content/drive')

#Carichiamo il modello RAG ottimizzato
model_name = "sentence-transformers/multi-qa-MiniLM-L6-cos-v1"
retriever_model = SentenceTransformer(model_name)
print(f"✅ Modello RAG {model_name} caricato correttamente!")

#Percorso della cartella con i file JSON
dataset_folder = Path("json_files/")

#Verifica dell'esistenza della cartella
if not dataset_folder.exists():
    raise FileNotFoundError(f"❌ Errore: la cartella {dataset_folder} non esiste!")

#Carichiamo i dati dai file JSON
all_data = []

for file_path in dataset_folder.glob("*.json"):
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            data = json.load(f)
            all_data.extend(data if isinstance(data, list) else [data])
    except Exception as e:
        print(f"⚠️ Errore nel caricamento del file {file_path.name}: {e}")

#Convertiamo i dati in un DataFrame
df = pd.DataFrame(all_data)

#Verifica del caricamento corretto
if df.empty:
    raise ValueError("❌ Errore: il dataset è vuoto! Verifica i file JSON.")
else:
    print(f"✅ {len(df)} documenti caricati!")
    print("🔍 **Colonne disponibili nel dataset:**", df.columns.tolist())

#Creiamo la colonna `full_text` (combinazione di titolo e abstract)
if {"Title", "Abstract"}.issubset(df.columns):
    df["full_text"] = df[["Title", "Abstract"]].astype(str).agg(" ".join, axis=1)
elif "Title" in df.columns:
    df["full_text"] = df["Title"].astype(str)
    print("⚠️ 'Abstract' non trovato, uso solo 'Title' per 'full_text'.")
elif "Abstract" in df.columns:
    df["full_text"] = df["Abstract"].astype(str)
    print("⚠️ 'Title' non trovato, uso solo 'Abstract' per 'full_text'.")
else:
    raise KeyError("❌ Errore: Nessuna delle colonne richieste è presente!")

#Formattazione semplificata: NomeCategoria:Qy;NomeCategoria2:Qz
if "Categories" in df.columns:
    def format_categories(catlist):
        if isinstance(catlist, list):
            return ";".join([
                f"{cat.get('Description', '').strip()}:{cat.get('Quartile', '').strip()}"
                for cat in catlist if isinstance(cat, dict)
            ])
        return ""
    df["CategoriesFormatted"] = df["Categories"].apply(format_categories)
else:
    df["CategoriesFormatted"] = ""


#Generazione degli embedding per FAISS
print("⚙️ Generazione degli embedding in corso...")
document_embeddings = retriever_model.encode(df["full_text"].tolist(), convert_to_numpy=True)
print(f"✅ {len(document_embeddings)} embedding generati!")

#Creazione dell'indice FAISS
embedding_dim = document_embeddings.shape[1]
index = faiss.IndexFlatL2(embedding_dim)
index.add(document_embeddings)
print(f"\n✅ Indice FAISS creato con {index.ntotal} documenti indicizzati!")

def search_rag(query, top_k=5):
    """Interroga FAISS con una query ottimizzata e restituisce i documenti più pertinenti."""

    #Pre-processiamo la query per il retrieval
    print(f"🔎 **Query originale:** {query}")

    #Generiamo l'embedding della query
    query_embedding = retriever_model.encode([query], convert_to_numpy=True)

    #Cerchiamo i documenti più vicini alla query
    distances, indices = index.search(query_embedding, top_k)

    #Recuperiamo i documenti corrispondenti
    retrieved_docs = []
    for idx in indices[0]:
        doc = {
            "Title": df.iloc[idx].get("Title", "N/A"),
            "Authors": df.iloc[idx].get("Authors", "Unknown"),
            "Year": df.iloc[idx].get("PublicationYear", "Unknown"),
            "Abstract": df.iloc[idx].get("Abstract", "No abstract available"),
            "Doi": df.iloc[idx].get("Doi", "Not available"),
            "PdfUrl": df.iloc[idx].get("PdfUrl", "No link available"),
            "Categories": df.iloc[idx].get("CategoriesFormatted", "")
        }
        retrieved_docs.append(doc)

    # Stampa risultati
    print("\n📚 Documenti Recuperati:")
    for doc in retrieved_docs:
        print(f"\n📖 Titolo: {doc['Title']}")
        print(f"👨‍🔬 Autori: {doc['Authors']}")
        print(f"📅 Anno: {doc['Year']}")
        print(f"📜 Abstract: {doc['Abstract'][:300]}...")
        if doc['Doi'] != "Not available":
            print(f"🔗 DOI: {doc['Doi']}")
        if doc['PdfUrl'] != "No link available":
            print(f"📂 PDF: {doc['PdfUrl']}")

#Testiamo la ricerca con query ottimizzata
search_rag("Critical step heart transplant")